### PR TITLE
cleanup product server

### PR DESCRIPTION
**Pull request by Ladywiz09**

### CODE REVIEW

**Comment by Ladywiz09** [comment]
I'm not sure how to add my json file for this assignment.

**Review by jboursiquot — CHANGES_REQUESTED** [review]
Good first pass. Now add the remaining handlers.

**Comment by Ladywiz09** [comment]
Updated cleanup product server changes

**Review by jboursiquot — APPROVED** [review]
Good. You still need to add the remaining handlers.

**Pull request merged**
